apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora
  namespace: nextcloud
  labels:
    app: collabora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collabora
  template:
    metadata:
      labels:
        app: collabora
    spec:
      containers:
        - name: collabora
          image: collabora/code:24.04.9.2.1
          ports:
            - containerPort: 9980
              name: collabora
          env:
            # WICHTIG: Erlaubte Nextcloud-Domains - HTTPS auf Port 30443
            - name: aliasgroup1
              value: "https://192.168.178.63:30443"
            
            # Server-Name für externe Erreichbarkeit
            - name: server_name
              value: "192.168.178.63:30981"
            
            # SSL deaktivieren (wird durch NGINX Proxy gehandhabt)
            - name: extra_params
              value: "--o:ssl.enable=false --o:ssl.termination=true"
            
            - name: DONT_GEN_SSL_CERT
              value: "true"
            
            # Admin-Konsole
            - name: username
              value: admin
            - name: password
              valueFrom:
                secretKeyRef:
                  name: collabora-secret
                  key: admin-password
          
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          
          securityContext:
            capabilities:
              add:
                - MKNOD
---
apiVersion: v1
kind: Service
metadata:
  name: collabora
  namespace: nextcloud
  labels:
    app: collabora
spec:
  type: ClusterIP  # Änderung: ClusterIP statt NodePort
  selector:
    app: collabora
  ports:
    - name: collabora
      port: 9980
      targetPort: 9980