apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 33:33 /var/www/html"]
          volumeMounts:
            - name: html
              mountPath: /var/www/html
      
      containers:
        - name: nextcloud
          image: nextcloud:31.0.4-apache
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: mariadb.nextcloud.svc.cluster.local:3306
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              value: nextcloud
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: password            
            - name: NEXTCLOUD_ADMIN_USER
              value: admin
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin-secret
                  key: password    
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "nextcloud.ewe-netz-backup.de localhost nextcloud.nextcloud.svc.cluster.local"
            - name: OVERWRITEHOST
              value: "nextcloud.ewe-netz-backup.de"
            - name: OVERWRITEPROTOCOL
              value: "https"
            - name: OVERWRITECLIURL
              value: "https://nextcloud.ewe-netz-backup.de"      
            - name: REDIS_HOST
              value: nextcloud-redis.nextcloud.svc.cluster.local
            - name: REDIS_HOST_PORT
              value: "6379"
            - name: REDIS_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: REDIS_PASSWORD          
          volumeMounts:
            - name: html
              mountPath: /var/www/html
            - name: collabora-config
              mountPath: /var/www/html/config/collabora.config.php
              subPath: collabora.config.php          
          livenessProbe:
            httpGet:
              path: /status.php
              port: 80
              httpHeaders:
                - name: Host
                  value: "nextcloud.ewe-netz-backup.de"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3          
          readinessProbe:
            httpGet:
              path: /status.php
              port: 80
              httpHeaders:
                - name: Host
                  value: "nextcloud.ewe-netz-backup.de"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3          
          resources:
            requests:
              cpu: 100m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi      
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: nextcloud-html
        - name: collabora-config
          configMap:
            name: nextcloud-config
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  type: ClusterIP  
  selector:
    app: nextcloud
  ports:
    - port: 80
      targetPort: 80