apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 33:33 /var/www/html"]
          volumeMounts:
            - name: html
              mountPath: /var/www/html
        
        - name: install-collabora-app
          image: nextcloud:31.0.4-apache
          command: 
            - sh
            - -c
            - |
              # Warte bis Nextcloud installiert ist
              while [ ! -f /var/www/html/config/config.php ]; do
                echo "Warte auf Nextcloud-Installation..."
                sleep 5
              done
              
              echo "Konfiguriere Talk App - Signaling Mode..."
              php /var/www/html/occ config:app:set spreed signaling_mode --value="external"
              
              echo "Konfiguriere Trusted Proxies..."
              php /var/www/html/occ config:system:set trusted_proxies 0 --value="10.0.0.0/8"
              php /var/www/html/occ config:system:set trusted_proxies 1 --value="172.16.0.0/12"
              php /var/www/html/occ config:system:set trusted_proxies 2 --value="192.168.0.0/16"
              php /var/www/html/occ config:system:set forwarded_for_headers 0 --value="HTTP_X_FORWARDED_FOR"
              
              echo "Konfiguriere Trusted Domains..."
              php /var/www/html/occ config:system:set trusted_domains 0 --value="192.168.178.63:30443"
              php /var/www/html/occ config:system:set trusted_domains 1 --value="localhost"
              php /var/www/html/occ config:system:set trusted_domains 2 --value="nextcloud.nextcloud.svc.cluster.local"
              

              # Installiere Collabora App
              php /var/www/html/occ app:install richdocuments || true
              php /var/www/html/occ app:enable richdocuments || true
              
              echo "Installiere Talk App..."
              php /var/www/html/occ app:install spreed || true
              php /var/www/html/occ app:enable spreed || true

              # Konfiguriere Collabora-Server
              php /var/www/html/occ config:app:set richdocuments wopi_url --value="http://collabora.nextcloud.svc.cluster.local:9980"

              # HPB Signaling Server konfigurieren
              php /var/www/html/occ config:app:set spreed signaling_servers --value='[{"server":"https://192.168.178.63:30444","verify":false}]'
              
              cho "Konfiguriere Talk App - TURN Server..."
              php /var/www/html/occ config:app:set spreed turn_servers --value='[{"schemes":"turn","server":"192.168.178.63","port":"30478","secret":"0d3e50717c9fff2263babeec3a8b3b86e33252822162642cb35a758087fb76e0","protocols":"udp,tcp"}]'
              
              echo "Collabora konfiguriert!"
          volumeMounts:
            - name: html
              mountPath: /var/www/html
      
      containers:
        - name: nextcloud
          image: nextcloud:31.0.4-apache
          ports:
            - containerPort: 80
          env:
            # Datenbank-Konfiguration
            - name: MYSQL_HOST
              value: mariadb.nextcloud.svc.cluster.local:3306
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              value: nextcloud
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: password
            
            # Admin-User automatisch anlegen
            - name: NEXTCLOUD_ADMIN_USER
              value: admin
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin-secret
                  key: password
            
            # Automatische Installation aktivieren
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "192.168.178.63:30443 localhost nextcloud.nextcloud.svc.cluster.local"
            - name: OVERWRITEHOST
              value: "192.168.178.63:30443"
            - name: OVERWRITEPROTOCOL
              value: "https"
            - name: OVERWRITECLIURL
              value: "https://192.168.178.63:30443"
            
            # Redis-Konfiguration
            - name: REDIS_HOST
              value: nextcloud-redis.nextcloud.svc.cluster.local
            - name: REDIS_HOST_PORT
              value: "6379"
            - name: REDIS_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: REDIS_PASSWORD
          
          volumeMounts:
            - name: html
              mountPath: /var/www/html
            - name: collabora-config
              mountPath: /var/www/html/config/collabora.config.php
              subPath: collabora.config.php
          
          livenessProbe:
            httpGet:
              path: /status.php
              port: 80
              httpHeaders:
                - name: Host
                  value: "192.168.178.63:30080"
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /status.php
              port: 80
              httpHeaders:
                - name: Host
                  value: "192.168.178.63:30080"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
      
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: nextcloud-html
        - name: collabora-config
          configMap:
            name: nextcloud-config
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  type: ClusterIP  
  selector:
    app: nextcloud
  ports:
    - port: 80
      targetPort: 80