---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-admin-secret
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/component: app
spec:
  encryptedData:
    password: AgAYSj5lV/wwoZsDMVt0cDsnVUngn9lpkgWaVv4feiRgIL8ShpSa0JPVLeDrEFBidCYDk7vXpEQx96kz97zCe/kJShn8EdSqh+uTdS3aApsuOEbLsOcoFpnOJ6ehhEHJZs2M0UHetLX4jUq05jWkK7RTGjpdwBMnbcCY/j09ue2qru4M1JLiu/YsuO7FVdnKgP7bNrfvO9CKn5NZdCYUZcVmCSNVkQQXEHmznO1nnDk75bUULAj9TGyK1gHOHa6Kaz2hV4/c9UAKCvqsvmROnhOXdUi261/N6tyUPNMwVgurdL6UAqzhNW2a7fNtIeKPZq4eM86fFEmVV6Y153pATzPKDw/uVfso7eSKJdLdSjm5IqfES99PN5NIWQ3UMuJhExG7iMhZdEml9SpNuvjr87Wh/TdMAG1+FAhBbOmMQSSqSUU3RldDYT/fuwA4zx12uX93E3cowwLO4+i920ypLSOjuBGiWjJjiDslSU8oRsiiz2adC8RXSzVROVU7iCySLotmVF5+KQF9+xROY1Kves1OBSPGU3+FgbwbEFdYuIiUESFV3rP1Kl1n7EFBmIwS2gX9TzhrMAy7/Ylvw8uco06mgoG0nBKuQWazxPmzBIE3/P7VPfVaGr99/6Bop9l5GQuPs5LXbnMM7kUlfk2VcL+ZV42t2tkknZYyvK61CcUakVRV4pq4X/tx7Gum5Lki9xoHFCqySLRd1qLGI9cAUkH1
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-admin-secret
      namespace: nextcloud
      labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/component: app