# Talk HPB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-talk-hpb
  namespace: nextcloud
  labels:
    app: nextcloud-talk-hpb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-talk-hpb
  template:
    metadata:
      labels:
        app: nextcloud-talk-hpb
    spec:
      containers:
        - name: talk-hpb
          image: ghcr.io/nextcloud-releases/aio-talk:latest
          env:
            # Nextcloud Domain (deine externe IP/Domain)
            - name: NC_DOMAIN
              value: "nextcloud.nextcloud.svc.cluster.local"
            # WICHTIG: Erzwinge HTTP statt HTTPS
            - name: SKIP_VERIFY
              value: "true"
              
            # Talk/Signaling Host (deine externe IP)
            - name: TALK_HOST
              value: "192.168.178.63"
            
            # TURN Port
            - name: TALK_PORT
              value: "30478"
            
            # Secrets
            - name: TURN_SECRET
              valueFrom:
                secretKeyRef:
                  name: talk-hpb-secrets
                  key: TURN_SECRET
            - name: SIGNALING_SECRET
              valueFrom:
                secretKeyRef:
                  name: talk-hpb-secrets
                  key: SIGNALING_SECRET
            - name: INTERNAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: talk-hpb-secrets
                  key: INTERNAL_SECRET
          
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
            - name: turn-tcp
              containerPort: 3478
              protocol: TCP
            - name: turn-udp
              containerPort: 3478
              protocol: UDP
          
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          
          livenessProbe:
            httpGet:
              path: /api/v1/welcome
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30
          
          readinessProbe:
            httpGet:
              path: /api/v1/welcome
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
---
# Talk HPB Service (HTTP API)
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-talk-hpb
  namespace: nextcloud
  labels:
    app: nextcloud-talk-hpb
spec:
  type: NodePort
  selector:
    app: nextcloud-talk-hpb
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
      protocol: TCP