# Nextcloud Talk High Performance Backend (HPB) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-talk-hpb
  namespace: nextcloud
  labels:
    app: nextcloud-talk-hpb
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/component: talk-hpb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-talk-hpb
  template:
    metadata:
      labels:
        app: nextcloud-talk-hpb
    spec:
      containers:
        - name: signaling
          image: strukturag/nextcloud-spreed-signaling:latest
          command: ["/usr/bin/nextcloud-spreed-signaling"]
          args: ["--config", "/config/server.conf"]
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: signaling
          volumeMounts:
            - name: signaling-config
              mountPath: /config
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: signaling-config
          configMap:
            name: talk-hpb-signaling-config
---
# HPB Service (ClusterIP für internen Zugriff)
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-talk-hpb
  namespace: nextcloud
  labels:
    app: nextcloud-talk-hpb
spec:
  type: ClusterIP
  selector:
    app: nextcloud-talk-hpb
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: signaling
      port: 8081
      targetPort: 8081
      protocol: TCP