apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-cron
  namespace: nextcloud
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: fix-permissions
              image: busybox
              command: ["sh", "-c", "chown -R 33:33 /var/www/html"]
              volumeMounts:
                - name: nextcloud-html
                  mountPath: /var/www/html
          containers:
            - name: nextcloud-cron
              image: nextcloud:31.0.4-apache
              securityContext:
                runAsUser: 33
                runAsGroup: 33
              command: ["php", "-f", "/var/www/html/cron.php"]
              volumeMounts:
                - name: nextcloud-html
                  mountPath: /var/www/html
              securityContext:            # <-- add this block!
                runAsUser: 33
                runAsGroup: 33
          restartPolicy: OnFailure
          volumes:
            - name: nextcloud-html
              persistentVolumeClaim:
                claimName: nextcloud-html

